spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: rm550718
    password: 121003
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
